### ISSUE TITLE
ElementClickInterceptedException

### ISSUE THREAD

**Issue by joremysh** [penut85420/TranslationImprover#2]
environment: macOS 10.15.2
chrome version: 版本 83.0.4103.61 (正式版本) (64 位元)

`selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="javascript:void(0);" class="tlid-send-feedback-link">...</a> is not clickable at point (1256, 585). Other element would receive the click: <div class="notification-area">...</div>
  (Session info: chrome=83.0.4103.61)`

`Traceback (most recent call last):
  File "/Users/______/Documents/GitHub/TranslationImprover/main.py", line 21, in main
    driver.find_element_by_class_name('tlid-send-feedback-link').click()
  File "/Users/______/Documents/GitHub/TranslationImprover/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/______/Documents/GitHub/TranslationImprover/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/______/Documents/GitHub/TranslationImprover/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/______/Documents/GitHub/TranslationImprover/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)`

因為我在 Mac 上跑 main.py 一直出現這個錯誤，後來把下面這行改掉了。
`driver.find_element_by_class_name('tlid-send-feedback-link').click()`
變成下面這樣之後就可以正常跑了。
`element = driver.find_element_by_class_name('tlid-send-feedback-link')
            driver.execute_script("arguments[0].click();", element)`

**Comment by penut85420** [comment]
太感謝了！Windows 上這個地方也會有問題，但只是跳過而已
照你的方式修改之後就不會失敗了，我等等把程式碼 Push 上來

**Comment by penut85420** [comment]
This issue closed by 31e2cba00ea832b8052a143e5700d573c075a7de

**Comment by penut85420** [comment]
This issue closed by 31e2cba00ea832b8052a143e5700d573c075a7de
